### ISSUE TITLE
Exception: TypeError: Cannot read property '_route' of undefined at Vue.get (webpack-internal:///./node_modules/_vue-router@3.0.1@vue-router/dist/vue-router.esm.js:557:52) at Vue.remoteFunction (<anonymous>:2:14)

### ISSUE THREAD

**Issue by chiaweilee** [vuejs/vuex#1342]
### Version
3.0.1

### Reproduction link
[https://github.com/vuejs/vuex/issues/1341](https://github.com/vuejs/vuex/issues/1341)

### Steps to reproduce
var store = new Store()
store._vm.$router // undefined
store._vm.$route // undefined

### What is expected?
got $router and $route

### What is actually happening?
store._vm.$router // undefined
store._vm.$route // undefined

$route:[Exception: TypeError: Cannot read property '_route' of undefined at Vue.get (webpack-internal:///./node_modules/_vue-router@3.0.1@vue-router/dist/vue-router.esm.js:557:52) at Vue.remoteFunction (<anonymous>:2:14)]
$router:[Exception: TypeError: Cannot read property '_router' of undefined at Vue.get (webpack-internal:///./node_modules/_vue-router@3.0.1@vue-router/dist/vue-router.esm.js:553:52) at Vue.remoteFunction (<anonymous>:2:14)]

vue.esm.js?3153:591 [Vue warn]: Error in callback for watcher "function () { return getter(this$1.state, this$1.getters); }": "TypeError: Cannot read property '_router' of undefined"

---
Vue 2.5.16
vuex 3.0.1
vue-router 3.0.1

**Comment by DeVoresyah** [comment]
> 1. It's because store vm is not related with your application's root Vue instance which the router instance is injected.
> 2. You should not use `store._vm` since it's undocumented.

so, `store._vm` change to what??
can you help me, I've blueprint template but got same error like above
https://github.com/VoreCorporation/vuedonara-mix
