### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'state')     at Proxy.mappedState (vuex.esm-bundler.js:1162:31)

### ISSUE THREAD

**Issue by Krrunal** [vuejs/vuex#2226]
i am using vuex 4.1.0 with vue 3. I clone it in my node_modules using this

git clone https://github.com/vuejs/vuex.git node_modules/vuex
cd node_modules/vuex
yarn
yarn build

now when i run yarn run dev this error is occur

vuex.esm-bundler.js:1162 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'state')
    at Proxy.mappedState (vuex.esm-bundler.js:1162:31)
    at ReactiveEffect.run (reactivity.esm-bundler.js:178:19)
    at get value [as value] (reactivity.esm-bundler.js:1147:33)
    at Object.get [as routes] (chunk-3DFB6IXN.js:2745:22)
    at Object.get (chunk-3DFB6IXN.js:7249:23)
    at getter (chunk-3DFB6IXN.js:2854:90)
    at callWithErrorHandling (chunk-3DFB6IXN.js:186:32)
    at getter (chunk-3DFB6IXN.js:1572:22)
    at ReactiveEffect.getter [as fn] (chunk-3DFB6IXN.js:1595:29)
    at ReactiveEffect.run (reactivity.esm-bundler.js:178:19)
    
    how i solve this issue

**Comment by ffleandro** [comment]
I'm seeing this while migrating from Vue2 to Vue3, and Vuex 3 to 4.
Anyone has any hints?
