### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getters' of undefined

### ISSUE THREAD

**Issue by brainyl** [vuejs/vuex#264]
This error is thrown when you use any of the vuex helpers in a child component. From debugging, I noticed the store is not being injected into child components. For example, when I have this code in a child component, the error is thrown
```javascript
computed: {
   ...mapGetters({
    notifications: 'notification.all'
  })
}
```
I suspect there is breaking change with the current version of vuex and vue.

**Comment by ktsn** [comment]
I looked into it and the vuex store is injected into a child component certainly.
https://jsfiddle.net/0qmjcwmw/1/

It looks like you define the `all` getter in the `notification` module, but you should only give the getter name to `mapGetters`.

```js
computed: {
  ...mapGetters({
    notifications: 'all'
  }) 
}
```

Because all getters functions you defined on the store are gathered and flattened to `store.getters` object.

**Comment by brainyl** [comment]
@ktsn Thank you. The problem is not from my code, the sample above is a working code from a Vue 1.0 App. 'notifaction.all' is how I write my getters in a module, prefixing my methods with the module name. The issue is trying to call $store on a child component which throws that error:
```javascript
 res[key] = function mappedGetter() {
        if (!(val in this.$store.getters)) {
          console.error("[vuex] unknown getter: " + val);
        }
        return this.$store.getters[val];
      };
```
The same applies to mapState, mapActions etc. I tested your sample and even used Vue 2 and it works just fine. Maybe the problem is from my build tool (vue-loader). Just cannot get my head around it.

**Comment by ktsn** [comment]
Hmm, I am still not sure why it is happened...
Can you share your Vue and Vuex version, the code of your root component and Vuex store, and also build configuration?
I'll look into it deeper.

**Comment by brainyl** [comment]
Okay, thank you. I have created a gist for it, you can find it here https://gist.github.com/brainyl/e43dbe74916fc071dc99c1eff3f90274
http://github.com - automatic!
[GitHub](http://github.com)

**Comment by ktsn** [comment]
Thank you! I find the problem on my environment too.
I'll try to fix and let you know about the solution later :)

**Comment by brainyl** [comment]
Okay @ktsn. Thank you!

**Comment by ktsn** [comment]
@brainyl 
I realize the solution of this issue. Please try the following steps.

1. Add alias of `vue` in webpack.config

  ```js
  module.exports = {
    // ...
    resolve: {
      alias: {
        vue: 'vue/dist/vue.js'
      }
    },
    // ..
  }
  ```

2. Rewrite all `import Vue from 'vue/dist/vue.js'` to `import Vue from 'vue'`
3. Then it should work

The problem is caused by duplicated loading of vue.js.
Your code only loads the standalone build of vue.js (`import Vue from vue/dist/vue.js`) but vue-loader will load the runtime only build for hot reloading internally (`require('vue')` i.e. vue/dist/vue.common.js).
So, you can solve this problem by adding alias to standalone build.

**Comment by brainyl** [comment]
Thank you @ktsn. It is now working as expected. The Vue ecosystem is simply awesome!

**Comment by LinusBorg** [comment]
@ktsn @yyx990803 Do you guys think this can be avoided somehow, or is this something we should warn users about when explaining the differences about the different builds?

If the latter, it should probably be explained in the vue-loader doc as well as the webpack-specific template docs, right?

**Comment by ktsn** [comment]
@LinusBorg @yyx990803 
I guess it could be avoided by providing the runtime template compiler as a plugin instead of standalone build. But it might increase entire file size because both file might have shared util code.

```js
import Vue from 'vue' // runtime-only build
import compiler from 'vue-runtime-compiler' // load template compiler

Vue.use(compiler) // enable compiler
```

In any way, I think it should be explained on vue-loader (and vueify) doc because it is hard to solve if users face this problem.

**Comment by LinusBorg** [comment]
Agreed.

**Comment by yyx990803** [comment]
@ktsn @LinusBorg indeed, this probably should be noted on the installation page as well - basically, if using a module bundler, never do `import Vue from 'vue/dist/vue'`, but rather use the alias option in the bundler. /cc @chrisvfritz

**Comment by webnoob** [comment]
I am also experiencing this issue but am not using the build version of vue. In my code, I do `import Vue from 'vue'` and have the mapGetter in a globally included mixin. Is that supported?

**Comment by jartaud** [comment]
Same as @webnoob [comment](https://github.com/vuejs/vuex/issues/264#issuecomment-271838297)

**Comment by connor11528** [comment]
I also encountered this error and it was because I forgot to put `store` in my main Vue bootup (main.js) file like so:

```
new Vue({
  el: '#app',
  render: h => h(App),
  router,
  store
})
```

**Comment by node-monk** [comment]
@connor11528 THANK YOU!! After about 1hr of trying to figure out why mapGetters was not working, I came across your comment and checked my main.vue -- hand slap my own head :P

**Comment by webnoob** [comment]
@connor11528 I was also missing the Store in my bootup. Think it went missing when I was refactorying, whoops.

**Comment by shanemgrey** [comment]
I was thrown off by the fact that all my getters worked individually, but when I tried to use mapGetters, this is the error it failed with.  

I didn't have store in my `new Vue({...})` as others have noted. But I'm not sure I ever would have found that problem without this old, obscure, and closed issue. The error offers no clear indication that this might be the cause.  

I think there should be a note in the docs somewhere indicating either that store should always be in `new Vue({...})` when vuex is in use, or that it needs to be there if using the helpers.

**Comment by Prior99** [comment]
Just if anybody ever encounters this issue while using Vuex in Jest:

```
  "moduleNameMapper": {
    "vue$": "<rootDir>/node_modules/vue/dist/vue.js"
  },
```

solved a similar issue for me.

**Comment by Prior99** [comment]
It looks like this is related to the template compiler of either [vue-jest](https://github.com/vuejs/vue-jest) or [vue test utils](https://github.com/vuejs/vue-test-utils). When adding this mapper as described in my comment above this issue is solved, but child components are not mounted correctly anymore.

**Comment by irina9215** [comment]
@Prior99 It happened to me, the  similar issue.

**Comment by Prior99** [comment]
@irina9215 Are you using `createLocalVue`? For me removing that and using the default Vue fixed that (And not using the `moduleNameMapper`). See [this issue](https://github.com/vuejs/vue-test-utils/issues/790) in vue test utils.

**Comment by Austio** [comment]
I also ran into this when running in a non-compiled environment.  I setup this code sandbox to prove it worked. https://codesandbox.io/s/8knp1jm918

My Errors was that i was importing use `import Vue from 'vue/dist/vue.esm.browser';` in my main file but when i was using that in my vuex file i was doing `import Vue from 'vue';` After switching usage in vuex store file it worked

**Comment by DharunManivel** [comment]
TypeError: Cannot read property 'getters' of undefined
    at VueComponent.visitLists (pages_visits_index.js:55)
    at Watcher.get (commons.app.js:15219)
    at Watcher.evaluate (commons.app.js:15324)
    at VueComponent.computedGetter [as visitLists] (commons.app.js:15574)
    at Object.get (commons.app.js:12851)
    at Proxy.render (pages_visits_index.js:143)
    at VueComponent.Vue._render (commons.app.js:14310)
    at VueComponent.updateComponent (commons.app.js:14805)
    at Watcher.get (commons.app.js:15219)
    at new Watcher (commons.app.js:15208)

**Comment by lwisne** [comment]
Getting this as well. Try to run a trivial test and get a highly daunting internal error:

`TypeError: Cannot read property 'getters' of undefined
        at VueComponent.mappedGetter (/Users/lawrencewisne/Sites/demos/vuex-todomvc/node_modules/vuex/dist/vuex.common.js:887:73)
        at Watcher.get (/Users/lawrencewisne/Sites/demos/vuex-todomvc/node_modules/vue/dist/vue.runtime.common.dev.js:4442:25)
        at Watcher.evaluate (/Users/lawrencewisne/Sites/demos/vuex-todomvc/node_modules/vue/dist/vue.runtime.common.dev.js:4547:21)
        at VueComponent.computedGetter [as filteredTodos] (/Users/lawrencewisne/Sites/demos/vuex-todomvc/node_modules/vue/dist/vue.runtime.common.dev.js:4796:17)
        at VueComponent.incompleteCount (/Users/lawrencewisne/Sites/demos/vuex-todomvc/src/components/TodoMVC.vue:68:21)
        at Watcher.get (/Users/lawrencewisne/Sites/demos/vuex-todomvc/node_modules/vue/dist/vue.runtime.common.dev.js:4442:25)
        at Watcher.evaluate (/Users/lawrencewisne/Sites/demos/vuex-todomvc/node_modules/vue/dist/vue.runtime.common.dev.js:4547:21)
        at VueComponent.computedGetter [as incompleteCount] (/Users/lawrencewisne/Sites/demos/vuex-todomvc/node_modules/vue/dist/vue.runtime.common.dev.js:4796:17)
        at VueComponent.isZeroTodoCount (/Users/lawrencewisne/Sites/demos/vuex-todomvc/src/components/TodoMVC.vue:74:21)
        at Watcher.get (/Users/lawrencewisne/Sites/demos/vuex-todomvc/node_modules/vue/dist/vue.runtime.common.dev.js:4442:25)
        at Watcher.evaluate (/Users/lawrencewisne/Sites/demos/vuex-todomvc/node_modules/vue/dist/vue.runtime.common.dev.js:4547:21)
        at Proxy.computedGetter (/Users/lawrencewisne/Sites/demos/vuex-todomvc/node_modules/vue/dist/vue.runtime.common.dev.js:4796:17)
        at Proxy.render (/Users/lawrencewisne/Sites/demos/vuex-todomvc/src/components/TodoMVC.vue:101:842)
        at VueComponent.Vue._render (/Users/lawrencewisne/Sites/demos/vuex-todomvc/node_modules/vue/dist/vue.runtime.common.dev.js:3532:22)
        at VueComponent.updateComponent (/Users/lawrencewisne/Sites/demos/vuex-todomvc/node_modules/vue/dist/vue.runtime.common.dev.js:4036:21)
        at Watcher.get (/Users/lawrencewisne/Sites/demos/vuex-todomvc/node_modules/vue/dist/vue.runtime.common.dev.js:4442:25)
        at new Watcher (/Users/lawrencewisne/Sites/demos/vuex-todomvc/node_modules/vue/dist/vue.runtime.common.dev.js:4431:12)
        at mountComponent (/Users/lawrencewisne/Sites/demos/vuex-todomvc/node_modules/vue/dist/vue.runtime.common.dev.js:4043:3)
        at VueComponent.Object.<anonymous>.Vue.$mount (/Users/lawrencewisne/Sites/demos/vuex-todomvc/node_modules/vue/dist/vue.runtime.common.dev.js:8368:10)
        at Object.<anonymous> (/Users/lawrencewisne/Sites/demos/vuex-todomvc/test/unit/specs/TodoMVC.spec.js:8:32)
        at Object.asyncFn (/Users/lawrencewisne/Sites/demos/vuex-todomvc/node_modules/jest-jasmine2/build/jasmine_async.js:82:37)
        at resolve (/Users/lawrencewisne/Sites/demos/vuex-todomvc/node_modules/jest-jasmine2/build/queue_runner.js:52:12)
        at new Promise (<anonymous>)
        at mapper (/Users/lawrencewisne/Sites/demos/vuex-todomvc/node_modules/jest-jasmine2/build/queue_runner.js:39:19)
        at promise.then (/Users/lawrencewisne/Sites/demos/vuex-todomvc/node_modules/jest-jasmine2/build/queue_runner.js:73:82)
        at process._tickCallback (internal/process/next_tick.js:68:7)`

**Comment by lwisne** [comment]
Have this issue as well. Trying to run a trivial test and getting a horrible looking stack trace. :(

`TypeError: Cannot read property 'getters' of undefined
        at VueComponent.mappedGetter (node_modules/vuex/dist/vuex.common.js:887:73)
        at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:4442:25)
        at Watcher.evaluate (node_modules/vue/dist/vue.runtime.common.dev.js:4547:21)
        at Proxy.computedGetter (node_modules/vue/dist/vue.runtime.common.dev.js:4796:17)
        at Proxy.render (src/components/TodoList.vue:42:537)
        at VueComponent.Vue._render (node_modules/vue/dist/vue.runtime.common.dev.js:3532:22)
        at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:4036:21)
        at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:4442:25)
        at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:4431:12)
        at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:4043:3)
        at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8368:10)
        at init (node_modules/vue/dist/vue.runtime.common.dev.js:3112:13)
        at createComponent (node_modules/vue/dist/vue.runtime.common.dev.js:5935:9)
        at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:5882:9)
        at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6010:9)
        at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:5911:9)
        at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6010:9)
        at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:5911:9)
        at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6010:9)
        at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:5911:9)
        at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.runtime.common.dev.js:6432:7)
        at VueComponent.Vue._update (node_modules/vue/dist/vue.runtime.common.dev.js:3915:19)
        at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:4036:10)
        at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:4442:25)
        at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:4431:12)
        at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:4043:3)
        at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8368:10)
        at Object.<anonymous> (test/unit/specs/TodoMVC.spec.js:8:32)
        at Object.asyncFn (node_modules/jest-jasmine2/build/jasmine_async.js:82:37)
        at resolve (node_modules/jest-jasmine2/build/queue_runner.js:52:12)
        at new Promise (<anonymous>)
        at mapper (node_modules/jest-jasmine2/build/queue_runner.js:39:19)
        at promise.then (node_modules/jest-jasmine2/build/queue_runner.js:73:82)
        at process._tickCallback (internal/process/next_tick.js:68:7)`

**Comment by 3nuc** [comment]
This happened to me because of a circular import.

myfile.ts imported a store instance, but somewhere deep one of the store's submodules imported myfile.ts

Commenting out the line where myfile.ts imports the store fixed the issue

**Comment by bilalcapripio** [comment]
"TypeError: Cannot read property 'getters' of undefined"
