### ISSUE TITLE
Exception thrown during Vue update

### ISSUE THREAD

**Issue by ericremoreynolds** [vuejs/vuex#536]
Hello,

I am not sure if I've found a bug or if I'm doing something wrong.

Given the following code:

```html
<html>
  <body>
    <div id="vue">
      <div style="background: blue;" v-if="!message">Something</div>
      <div style="background: red;" v-if="message" v-text="message"></div>
      <button v-on:click="buttonClicked">Click me</button>
    </div>

    <script src="https://unpkg.com/vue@2.1.6/dist/vue.js"></script>

    <script>
    var vue = new Vue({
      el: '#vue',
      data: {
        message: null
      },
      methods: {
        buttonClicked: function() {
          this.message = "Hello @ " + new Date();
        }
      }
    });
    </script>
  </body>
</html>
```

I get the following error in Chrome Version 55.0.2883.95 (64-bit) when I click the button:

```
DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Object.removeChild (https://unpkg.com/vue@2.1.6/dist/vue.js:3825:8)
    at removeVnodes (https://unpkg.com/vue@2.1.6/dist/vue.js:4188:19)
    at patchVnode (https://unpkg.com/vue@2.1.6/dist/vue.js:4333:9)
    at updateChildren (https://unpkg.com/vue@2.1.6/dist/vue.js:4252:9)
    at patchVnode (https://unpkg.com/vue@2.1.6/dist/vue.js:4328:29)
    at Vue$3.patch [as __patch__] (https://unpkg.com/vue@2.1.6/dist/vue.js:4451:9)
    at Vue$3.Vue._update (https://unpkg.com/vue@2.1.6/dist/vue.js:2224:19)
    at Vue$3.<anonymous> (https://unpkg.com/vue@2.1.6/dist/vue.js:2191:10)
    at Watcher.get (https://unpkg.com/vue@2.1.6/dist/vue.js:1656:27)
    at Watcher.run (https://unpkg.com/vue@2.1.6/dist/vue.js:1725:22)
```

I'm appending the current date to the message only to prove that all JS execution stops after the first button click.

Strangely, the error doesn't happen if you drop the style attributes from the two divs.

Please let me know what's going on!

Thanks, best regards,

Eric

**Comment by ericremoreynolds** [comment]
Sorry just realised i posted this on the wrong repo.... my mistake
