### ISSUE TITLE
Exception: TypeError: rawGetter is not a function at wrappedGetter

### ISSUE THREAD

**Issue by gbgelado** [vuejs/vuex#573]
HELP!

I have this error when I try to use the getters:

> [Exception: TypeError: rawGetter is not a function at wrappedGetter (eval at <anonymous> (http://localhost:8080/app.js:948:2), <anonymous>:703:12) at Vue$3.computed.(anonymous function) (eval at <anonymous> (http://localhost:8080/app.js:948:2), <anonymous>:517:42) at Watcher.get (eval at <anonymous> (http://localhost:8080/app.js:600:2), <anonymous>:1661:27) at Watcher.evaluate (eval at <anonymous> (http://localhost:8080/app.js:600:2), <anonymous>:1769:21) at Vue$3.computedGetter [as play] (eval at <anonymous> (http://localhost:8080/app.js:600:2), <anonymous>:1967:15) at Object.get [as play] (eval at <anonymous> (http://localhost:8080/app.js:948:2), <anonymous>:519:42) at Object.remoteFunction (<anonymous>:3:14)]

Example on my component: 

`created () {`
`    console.log(this.$store.getters)`
`},`

My store:

`// store.js`
`import Vue from 'vue'`
`import Vuex from 'vuex'`
`import { BASE } from '../base'`

`Vue.use(Vuex)`

`const state = {`
`  BASE: BASE,`
`  loading: true`
`}`

`const getters = {`
 ` loading: state => {`
 `   return state.loading`
 ` }`
`}`

`const mutations = {`
 ` listGrades (state) {`
 `   return []`
 ` }`
`}`

`export default new Vuex.Store({`
 ` state,`
 ` getters,`
 ` mutations`
`})`

**Comment by ktsn** [comment]
Hi, thanks for filing this issue.
Please read [Issue Reporting Guideline](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening the issue. 
Specifically, minimal live reproduction on jsfiddle is helpful.

**Comment by lhas** [comment]
Hi,

This is happening with me too.

**Comment by ktsn** [comment]
Then, could you provide reproduction on jsfiddle or example code in github repository?
We cannot help you without any reproductions.

**Comment by fnlctrl** [comment]
Closing due to inactivity.

**Comment by jralph** [comment]
I'm getting this error when using babel es2015 preset. Without the preset, everything works fine. Dont know if that helps anyone.

**Comment by ktsn** [comment]
This seems same problem as #285.
