### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'commit' of undefined

### ISSUE THREAD

**Issue by yash2code** [vuejs/vuex#590]
Uncaught (in promise) TypeError: Cannot read property 'commit' of undefined
    at eval (eval at <anonymous> (http://localhost:8000/js/app.js:200:1), <anonymous>:22:48)
    at Array.forEach (native)
    at VueComponent.eval (eval at <anonymous> (http://localhost:8000/js/app.js:200:1), <anonymous>:21:38)
(anonymous) @ UnreadNots.vue?8e29:20
(anonymous) @ UnreadNots.vue?8e29:19

**Comment by yyx990803** [comment]
Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or JSBin containing a set of reproducible steps that can lead to the behavior you described.

Issues without proper reproduction steps cannot be triaged.
