### ISSUE TITLE
What does ModuleCollection.register do?

### ISSUE THREAD

**Issue by robbiemu** [vuejs/vuex#607]
I'm getting: 
```
vuex.js:291 Uncaught TypeError: Cannot read property 'modules' of undefined
    at ModuleCollection.register (http://localhost:8080/public/scripts/index.js:10615:16)
    at http://localhost:8080/public/scripts/index.js:10583:14
    at http://localhost:8080/public/scripts/index.js:10494:52
    at Array.forEach (native)
    at forEachValue (http://localhost:8080/public/scripts/index.js:10494:20)
    at new ModuleCollection (http://localhost:8080/public/scripts/index.js:10582:5)
    at new Store (http://localhost:8080/public/scripts/index.js:10667:19)
    at Object.11../modules/classes (http://localhost:8080/public/scripts/index.js:11216:19)
    at s (http://localhost:8080/public/scripts/index.js:1:254)
    at http://localhost:8080/public/scripts/index.js:1:305
```

with a pretty darn simple script.

My store:
```js
import Vue from 'vue';
import Vuex from 'vuex';

import {classes} from './modules/classes'

Vue.use(Vuex)

export default new Vuex.Store({
  actions: {
    loadData: ({commit}, dataSource) => {
      Vue.http.get(dataSource + '.json')
        .then(response => response.json())
        .then(data => {
          if(data) {
            console.log('[store] loadData - data returned', dataSource, data)
            switch(dataSource) {
              case 'Classes':
                commit('setClasses', data)
                break;
            }
          }
        })
    }
  },
  modules: {classes}
})
```

and its classes.js
```js
const state = {
  classes: {}
}

const getters = {
  getClasses: state => state.classes,
  getClass: (state, key) => state.classes[key]
}

const mutations = {
  setClasses: (state, classes) => state.classes = classes,
}

const actions = {
  initClasses: ({commit}) => {
    commit('loadData', 'Classes')
  }
}

export default {state, getters, mutations, actions}
```

This was compiled with gulp/browserify/vueify but so far as I know the output should be valid (there's no messing with async or generators here, import statements were the sort of work I needed babel for).

feel free to see attached [gist](https://gist.github.com/robbiemu/3ed664d2d283c95a2415168e98d23278) to see the output source and the gulpfile that generated it.

**Comment by ktsn** [comment]
As you export your module (classes.js) as default export, you need to import it as default module.
Please replace `import {classes} from './modules/classes'` with `import classes from './modules/classes'`
